dataloader:

  train_args:
    batch_size: 16
    num_workers: 8
    pin_memory: true
    shuffle: true
    persistent_workers: true
    prefetch_factor: 2


  val_args:
    batch_size: 16
    num_workers: 8
    pin_memory: true
    shuffle: false
    persistent_workers: true
    prefetch_factor: 2

  test_args:
    batch_size: 16
    num_workers: 8
    pin_memory: true
    shuffle: false
    persistent_workers: true
    prefetch_factor: 2
