run_training_func: "projects.ddq.src.run_training.run_training"

epochs: 70
max_iters: 0 # to be set from dataloader

optimizer:
  class: torch.optim.AdamW
  args:
    lr: 0.001
    betas: [0.9, 0.999]
    weight_decay: 0.0001
    no_decay_bn_filter_bias: true

scheduler:
  class: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    T_max: ${mul:${epochs},${max_iters}}
    eta_min: 1.0e-8
  warmup:
    enabled: true
    class: torch.optim.lr_scheduler.LinearLR
    args:
      start_factor: 1.0e-5
      end_factor: 1.0
      total_iters: 700

loss:
  class: projects.ddq.loss.DDQLoss
  args:
    main_criterion:
      class: projects.ddq.loss.AuxLoss
      args:
        cls:
          type: QualityFocalLoss
          use_sigmoid: true
          activated: true
          beta: 2.0
          loss_weight: 1.0
        bbox:
          type: GIoULoss
          loss_weight: 2.0
        train_cfg:
          assigner:
            type: TopkHungarianAssigner
            topk: 1
    aux_criterion:
      class: projects.ddq.loss.AuxLoss
      args:
        cls:
          type: QualityFocalLoss
          use_sigmoid: true
          activated: true
          beta: 2.0
          loss_weight: 1.0
        bbox:
          type: GIoULoss
          loss_weight: 2.0
        train_cfg:
          assigner:
            type: TopkHungarianAssigner
            topk: 8
